version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: suhel_lms_db
      POSTGRES_USER: suhel_user
      POSTGRES_PASSWORD: Suhel992910097
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "postgresql://suhel_user:Suhel992910097@db:5432/suhel_lms_db"
      NEXT_PUBLIC_APP_URL: "http://localhost:3000"
    depends_on:
      - db
    command: npm run dev

volumes:
  db_data: